name: Build LaTeX and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Version Name
        id: version_step
        run: echo "VERSION_TAG=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename PDF
        run: mv main.pdf CompNet_Notes.pdf

      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: "${{ env.VERSION_TAG }}"
          body: |
            Autobuild version: ${{ env.VERSION_TAG }}
            Date: ${{ steps.date.outputs.date }}
          files: CompNet_Notes.pdf
          draft: false
          prerelease: false